Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/LogSavePath
  LogFileName: app
  LogFileExt: .LogFileExt
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
JWT:
  Secret: qiusheng
  Issuer: blog-service
  Expire: 7200
Database:
  DBType: mysql
  UserName: root # 填写你的数据库账号
  Password: root123 # 填写你的数据数据库密码
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30